# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1fbfa95c5792db4f597b98bfa7d752293110cd0b6a5f924cd4604b681b9b59580ea65c6a094d1463b132cd34151dd581c9bc22a688fc97cbb9363dec60baaea1

test:
  secret_key_base: c1c3473ebde19d0dd61090f8ce3fd30f549176aa856bdddd1d118961c9a6d0c9eacc4bc62fc1871108887f86a85b67416fa4df974f162cd3eccb95778267ff11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
